### PR TITLE
LinkItONE support

### PR DESCRIPTION
**Pull request by wuulong**
Thanks your work to make this magic happen. 
These quick change tested with LinkItONE (https://labs.mediatek.com/site/global/developer_tools/mediatek_linkit/whatis_linkit/index.gsp)

The sample code checked with iPhone and Blynk 0.2.4, sound/UV sensor tested.

Working sample have figure: https://github.com/LinkItONEDevGroup/LASS/blob/master/Doc/Blynk_Example1.png

Remind that I am not full understand how your magic work. Hope this integration help.

Thanks.

### CODE REVIEW

**Comment by vshymanskyy** [comment]
Thanks for your efforts, but unfortunately I can't merge your request in it's current form (there are some incompatible changes right now).
I will try to build new integration based on the information you provided.
It would be great if you could check if it works after I finish... is this OK?

**Comment by MidTower** [comment]
Well, I believe a functional integration is not so important for me now as
I am am still in the steep learning curve on adruino side of things.

But, I am having trouble to register account for blynk apps, after
downloading it. And the website is currently not acccomodate for
registration? Hence I am kinda waiting , for information regarding
registration. As I am currently stuck at the login page of the apps.

I believe the information I given is xeebee, but at current stage,
communication through adruino with serial is sufficient for me.

Keep up the hard work.

**Comment by wuulong** [comment]
Related to LinkItONE support:

No problem, it seems you are making big changes. That's great!

I also like to verify if it can work on your new integration.
Please let me know when it happen.

BTW, the virtual PIN concept is great!
It only take very less time to integrate into current system.
Check this out! It works all because of you. Thanks.

https://github.com/LinkItONEDevGroup/LASS/blob/master/Doc/Blynk_Example2.png


On Sat, Jul 18, 2015 at 5:25 AM, Volodymyr Shymanskyy <
notifications@github.com> wrote:

> Thanks for your efforts, but unfortunately I can't merge your request in
> it's current form (there are some incompatible changes right now).
> I will try to build new integration based on the information you provided.
> It would be great if you could check if it works after I finish... is this
> OK?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blynkkk/blynk-library/pull/16#issuecomment-122422142>.
>



-- 
許武龍 ( wuulong )
專業認證：IBM Certificated Linux Trainer for  LPIC, Security
Engineer(TWCERT/CC), JAVA Programmer(SCJP)
Interest: Maker, Embedded System, Rototics

**Comment by vshymanskyy** [comment]
Hey @wuulong, please check the latest version, I added LinkItObe support.
But I couldn't even check if it compiles, as I'm using linux and they don't provide any support for this.
So... please check it and tell if there are any problems

**Comment by wuulong** [comment]
Thanks and Great. Will check it out and feedback to you.

On Thu, Jul 30, 2015 at 7:54 AM, Volodymyr Shymanskyy <
notifications@github.com> wrote:

> Hey @wuulong <https://github.com/wuulong>, please check the latest
> version, I added LinkItObe support.
> But I couldn't even check if it compiles, as I'm using linux and they
> don't provide any support for this.
> So... please check it and tell if there are any problems
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blynkkk/blynk-library/pull/16#issuecomment-126131607>.
>



-- 
許武龍 ( wuulong )
專業認證：IBM Certificated Linux Trainer for  LPIC, Security
Engineer(TWCERT/CC), JAVA Programmer(SCJP)
Interest: Maker, Embedded System, Rototics

**Comment by vshymanskyy** [comment]
Actually we are ready for release... So it would be good if you could check it so it could fall into current release.

**Comment by wuulong** [comment]
Plan to check it in the weekend, hope this is OK for you.

BTW, also post this news to LinkItONE Taiwan community, maybe others
developer will feedback also. Of course, promote  Blynk at the same time.

Thanks for your great project.


On Fri, Jul 31, 2015 at 3:53 AM, Volodymyr Shymanskyy <
notifications@github.com> wrote:

> Actually we are ready for release... So it would be good if you could
> check it so it could fall into current release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blynkkk/blynk-library/pull/16#issuecomment-126456728>.
>



-- 
許武龍 ( wuulong )
專業認證：IBM Certificated Linux Trainer for  LPIC, Security
Engineer(TWCERT/CC), JAVA Programmer(SCJP)
Interest: Maker, Embedded System, Rototics

**Comment by vshymanskyy** [comment]
Absolutely no problem, thank you!

**Comment by vshymanskyy** [comment]
Hey @wuulong, any updates?
0.3.0 is out and i'm wondering if I need to do any changes...

**Comment by wuulong** [comment]
Hey Volodymyr Shymanskyy,

   I loss the chance to check it last weekend, will do it asap.

   I saw your release note, it's great. LinkItONE is on the list.

   Any way, the information already post to LinkItONE community.
   No matter what, we will get more check results from community.

   Thanks for your works.

On Thu, Aug 6, 2015 at 4:06 AM, Volodymyr Shymanskyy <
notifications@github.com> wrote:

> Hey @wuulong <https://github.com/wuulong>, any updates?
> 0.3.0 is out and i'm wondering if I need to do any changes...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blynkkk/blynk-library/pull/16#issuecomment-128132641>.
>



-- 
許武龍 ( wuulong )
專業認證：IBM Certificated Linux Trainer for  LPIC, Security
Engineer(TWCERT/CC), JAVA Programmer(SCJP)
Interest: Maker, Embedded System, Robotics

**Pull request closed without merging**
