### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Gius-8**

### CODE REVIEW

**Comment by vshymanskyy** [comment]
Sorry, most probably we cannot accept this request - your users will have to use ESP8266 Shield example, it looks compatible enough.

**Comment by Gius-8** [comment]
Hi @vshymanskyy , why not? I only did it to make the code more simple to users who use Blynk with my board.

**Comment by vshymanskyy** [comment]
First, because of code duplication, second because of support - we don't have hardware to test it.
Also, you can just provide a proper Blynk example with your other libraries...

**Comment by Gius-8** [comment]
OK! I got it. I will try to ship you a board. Meanwhile, thank you so much 😃

**Pull request closed without merging**
