### PR TITLE
Added examples sketches for RTL8195A/RTL8711AM chipsets

### PR DESCRIPTION
**Pull request by narioinc**
### Description
This pull request aims at extending the support for the REALTEK wifi chipsets. The PR contains a basic example sketch and the associated header file changes for REALTEK 8195A/8711AM based boards. The example has been tested on the RAK creator pro boards (powerted by the RTL8711AM) and also on the official REALTEK Ameba 8195AM dev board. 

### Issues Resolved
This pull request is for an enhancement and hence there are no issues resolved as such

### CODE REVIEW

**Comment by vshymanskyy** [comment]
Thanks for your PR!
AFAIK, `BlynkWifi` could be reused from existing implementation, I don't think we need code duplication here. What do you think?

**Comment by narioinc** [comment]
Aah Yes!!
A complete oversight from my end. I can very well use the BlynkWifiCommon.h :)

Yes I would definitely agree that this is a code duplication and hence the PR can be ignored. I will edit the tutorial @ hackster.io as well to encourage users to use the BlynkWifiCommon.h 

Thanks for taking your time to review :)

Regards
Naresh K

**Comment by narioinc** [comment]
I have made the necessary changes in my tutorial here:
https://www.hackster.io/naresh-krish/connecting-your-rak-creator-pro-with-blynk-services-a3a37e

To use BlynkSimpleWifi.h !!

:) Naresh k

**Comment by vshymanskyy** [comment]
@narioinc please don't hurry ;) I'll send you an email

**Pull request closed without merging**
