### PR TITLE
Covered +10 examples with PlatformIO + Travis.CI

### PR DESCRIPTION
**Pull request by ivankravets**
Build result https://travis-ci.org/ivankravets/blynk-library/builds/180386117

### CODE REVIEW

**Comment by doom369** [comment]
@ivankravets don't know what is that :). But thanks.

**Comment by vshymanskyy** [comment]
Why did you merge it, I should have checked that?

**Comment by doom369** [comment]
@vshymanskyy it was a joke. However I didn't check it. My bad.

**Comment by ivankravets** [comment]
Guys, this PR doesn't affect library code. It is mostly related to CI.

P.S: @vshymanskyy please remove `write` permissions from @doom369 for this repo :joy_cat: :joy_cat: :joy_cat:

**Comment by vshymanskyy** [comment]
Thanks, the PR is good actually. I'll fix some small issues later.

**Pull request merged**
