### PR TITLE
Added Board Support for Seeed Wio Terminal dev board

### PR DESCRIPTION
**Pull request by ansonhe97**
### Description
I've added a simple board support for Seeed [Wio Terminal](https://www.seeedstudio.com/Wio-Terminal-p-4509.html). Not sure if there is any more work to be done, please kindly let me know.

Wio Terminal uses the Realtek RTL8720DN as wifi core and here is the Wi-Fi wiki: https://wiki.seeedstudio.com/Wio-Terminal-Wi-Fi/

### Issues Resolved
N/a

### CODE REVIEW

**Comment by blynkkk** [comment]
Please contact iot@blynk.cc regarding adding the board.

Thanks!

**Comment by ansonhe97** [comment]
> Please contact [iot@blynk.cc](mailto:iot@blynk.cc) regarding adding the board.
> 
> Thanks!

Sent :D

**Comment by Pillar1989** [comment]
This PR is very useful and I think I need it. @blynkkk

**Comment by ansonhe97** [comment]
Also added Bluetooth Feature for Wio Terminal.

**Pull request merged**
