### PR TITLE
LaunchPad CC3200 extension for Blynk

### PR DESCRIPTION
**Pull request by rei-vilo**
LaunchPad CC3200 extension for Blynk

### CODE REVIEW

**Comment by vshymanskyy** [comment]
Hi. thank you!
It looks like there is nothing specific about this board, one our our generic handlers would do.
I will start working on this as soon as we get those TI boars...

**Comment by rei-vilo** [comment]
You're welcome! There's one hardware limitation with the CC3200, but not WiFi-related: analog inputs are limited to 1.5 V. Higher voltage zombify the MCU. 

One very nice thing about the code: it works on the CC3200 and on the CC3100 BoosterPack (= shield) plugged on any other LaunchPad (= board). It only requires adding `#include "SPI.h"`, as the connection between the MCU and the CC3100 WiFi radio is done through the SPI bus. On the CC3200, the connection internal and thus doesn't require the SPI bus.

**Comment by vshymanskyy** [comment]
I just added support for generic Energia WiFi + RedBearLab CC3200.
Could you please check if general Energia WiFi works for you?

**Comment by rei-vilo** [comment]
I tested the committed Energia_WiFi.ino with BlynkSimpleEnergiaWiFi.h on a MSP432 LaunchPad + CC3100 BoosterPack. It works great!

The CC3100 is a CC3200 without the MCU, only the WiFi. The CC3100 BoosterPack is a shield for all the LaunchPads. 

Now, I'm using the `Generic Board` on my iPhone, and the pins numbers don't go high enough. The MSP432 LaunchPad has 78 pins, the TM4C129 LaunchPad (with Ethernet) 95 pins... Please find [here](http://energia.nu/pin-maps/) the pins maps for all those boards.

**Comment by rei-vilo** [comment]
Some questions:

* I noticed you haven't committed the definitions I wrote for the LaunchPad CC3200 `BlynkCC3200.h` and `LaunchPad-CC3200.json`. Do you plan to include them, as well as for other LaunchPads?

* On the iOS app, do you plan to list the `LaunchPad CC3200` and other LaunchPad boards to make them easier to use?

**Comment by vshymanskyy** [comment]
Hi. Sorry you were actually a bit late for this release.
Great to hear it worked!
Sure, we will add the json description files soon, but we need to do some test with the boards before we add them to the app. Still waiting for TI boards...

**Comment by rei-vilo** [comment]
Thank you for supporting the CC3200 and other LaunchPad boards from Texas Instruments.

**Comment by sergicuen** [comment]
Hi, rei-vilo,
I´m trying to compile Energia_WiFi.ino for a MSP430+CC3100 using Energia, as you mention before.
Settings are: 
Board->Launchpad w/ msp430f5529

**Comment by rei-vilo** [comment]
Could you be more specific about the errors?

Please note the MSP430F5529 isn't part of the MCUs listed, only the CC3200 and the MSP432. 

> It looks like there is nothing specific about this board, one our our generic handlers would do.

Please use the library from the main branch, not my pull-request, as the library uses one of their generic handlers. Finally, contact the Blynk team directly.

**Comment by sergicuen** [comment]
Thanks for your answer.
You are right, I mistook MSP430 (16bit cpu) for MSP432 (arm cpu).
I tried compilation with the last Blynk library (Blynk_v0.3.1) with the following result for MSP430 (please see below).
Nevertheless, I was looking for the procedure to develop the support files for a new board in the blynk site without any success. Do you have any docs about it?
TIA

In file included from C:\ti\energia-0101E0017\hardware\msp430\libraries\blynk-library-master/Blynk/BlynkApi.h:16:0,
                 from C:\ti\energia-0101E0017\hardware\msp430\libraries\blynk-library-master/BlynkApiArduino.h:14,
                 from C:\ti\energia-0101E0017\hardware\msp430\libraries\blynk-library-master/Adapters/BlynkWiFiCommon.h:18,
                 from C:\ti\energia-0101E0017\hardware\msp430\libraries\blynk-library-master/BlynkSimpleEnergiaWiFi.h:15,
                 from Energia_WiFi.cpp:26:
C:\ti\energia-0101E0017\hardware\msp430\libraries\blynk-library-master/Blynk/BlynkParam.h: In member function 'double BlynkParam::iterator::asDouble() const':
C:\ti\energia-0101E0017\hardware\msp430\libraries\blynk-library-master/Blynk/BlynkParam.h:37:58: error: 'atof' was not declared in this scope
C:\ti\energia-0101E0017\hardware\msp430\libraries\blynk-library-master/Blynk/BlynkParam.h: In member function 'double BlynkParam::asDouble() const':
C:\ti\energia-0101E0017\hardware\msp430\libraries\blynk-library-master/Blynk/BlynkParam.h:68:55: error: 'atof' was not declared in this scope

**Comment by rei-vilo** [comment]
The library with `atof` seems to be missing.

When I ported Blynk to the CC3200, I took the original library for Arduino and adapted it. Which board are you considering? 

Please note I'm not member of the Blynk team. Feel free to contact the Blynk team on the [forum](http://community.blynk.cc).

**Comment by sergicuen** [comment]
MSP430F5529 (25MHz) + CC3100 
This is the educational pack recomended by TI.
I will try in the Blynk forum.
Thanks a lot

**Pull request closed without merging**
