### PR TITLE
Added support for Arduino MKRGSM 1400

### PR DESCRIPTION
**Pull request by Rocketct**
hi @vshymanskyy,

**Description**

Implemented the support file, required to make works Blynk with Arduino MKRGSM 1400:
- Implemented the .adapter class;
- Implemented the the header file BlynkSimpleMKRGSM.h;
- Implemented the example Example/Boards_GSM/Arduino_MKRGSM/Arduino_MKRGSM.ino 

**Issues Resolved**
use the native library MKRGSM instead of tinyGSM

### CODE REVIEW

**Comment by Rocketct** [comment]
Hi @vshymanskyy  have we any update on this PR and the support for NB1500 one?

**Comment by vshymanskyy** [comment]
@Rocketct thanks for the PR. Will review this on the weekend!

**Comment by Rocketct** [comment]
Ok really thank you about your availability @vshymanskyy

**Comment by vshymanskyy** [comment]
@Rocketct I'm ready to merge these requests.
I'm able to validate only the MKR 1400 integration, as I only have this board.

As the PRs are simple enough, so we would highly appreciate if Arduino can resign copyrights for #443 and #445 (you can still have the Author signature).
If not, it would be easier for us to add this integration and not to deal with legal complications later (having multiple copyright holders).

**Comment by vshymanskyy** [comment]
@Rocketct I have merged the requests, I'll now do some additional tweaks and release the library.

**Comment by Rocketct** [comment]
ok really thank you.

**Comment by vshymanskyy** [comment]
@Rocketct done

**Pull request merged**
